###############
### SOURCES ###
###############

### Do not change
source = ~/.local/share/dotfiles/default/hypr/conf/autostart.conf
source = ~/.local/share/dotfiles/default/hypr/conf/looknfeel.conf
source = ~/.local/share/dotfiles/default/hypr/conf/windowrules.conf
source = ~/.local/share/dotfiles/default/hypr/conf/layerrules.conf
source = ~/.local/share/dotfiles/current/theme/hyprland.conf

### Can change these, create more files and import here if needed
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
# source = ~/.config/hypr/my_custom_file.conf
exec-once = hyprpaper & sleep 0.5 && hyprctl monitors -j | jq -r '.[].name' | xargs -I {} hyprctl hyprpaper wallpaper "{},/home/mbp/.local/share/dotfiles/current/background"
# exec-once = clone mount gdrive: ~/GoogleDrive --vfs-cache-mode full --allow-other --volname "Google Drive" --daemon
