#!/bin/bash

set -e

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$SCRIPT_DIR/lib/helpers.sh"
DOTFILES_DIR="$HOME/.local/share/dotfiles"

# Set initial theme
log_info "Setting up initial theme (osaka-jade)..."
mkdir -p "$DOTFILES_DIR/current"
ln -snf "$DOTFILES_DIR/themes/osaka-jade" "$DOTFILES_DIR/current/theme"

rm -f "$DOTFILES_DIR/current/background"
ln -snf "$DOTFILES_DIR/current/theme/backgrounds/1-osaka-jade-bg.jpg" "$DOTFILES_DIR/current/background"

# Set up SDDM
log_info "Setting up sddm ..."
SDDM_THEME_SRC="$DOTFILES_DIR/default/sddm/themes/mbp"
SDDM_THEME_DEST="/usr/share/sddm/themes/"

if command -v sddm &>/dev/null; then
  if [ -d "${SDDM_THEME_DEST}mbp" ]; then
    sudo rm -rf "${SDDM_THEME_DEST}mbp"
  fi

  sudo cp -r "$SDDM_THEME_SRC" "$SDDM_THEME_DEST"
  sudo chown -R $USER:$USER "${SDDM_THEME_DEST}mbp"
fi

mkdir -p "$HOME/.config/nvim/lua/plugins"
mkdir -p "$HOME/.config/btop/themes"
mkdir -p "$HOME/.config/mako"

ln -snf "$DOTFILES_DIR/current/theme/neovim.lua" "$HOME/.config/nvim/lua/plugins/theme.lua"
ln -snf "$DOTFILES_DIR/current/theme/btop.theme" "$HOME/.config/btop/themes/current.theme"
ln -snf "$DOTFILES_DIR/current/theme/mako.ini" "$HOME/.config/mako/config"

mkdir -p "$HOME/.config/fastfetch"
ln -snf "$DOTFILES_DIR/config/fastfetch/configs/config-default.jsonc" "$HOME/.config/fastfetch/config.jsonc"

log_info "Setting up wallpapers symlink..."
mkdir -p "$HOME/Pictures"

# If old backup dir exists => remove to avoid `mv` creating duplicated dir
if [ -e "$HOME/Pictures/dotfiles-wallpapers-backup" ] || [ -L "$HOME/Pictures/dotfiles-wallpapers-backup" ]; then
  rm -rf "$HOME/Pictures/dotfiles-wallpapers-backup"
fi

# If there exists symlink or old dir => turn it to backup
if [ -L "$HOME/Pictures/dotfiles-wallpapers" ] || [ -d "$HOME/Pictures/dotfiles-wallpapers" ]; then
  mv "$HOME/Pictures/dotfiles-wallpapers" "$HOME/Pictures/dotfiles-wallpapers-backup"
fi

# Good practice to add -n (--no-dereference) when working with directory
ln -snf "$DOTFILES_DIR/backgrounds" "$HOME/Pictures/dotfiles-wallpapers"
log_detail "Wallpapers symlinked to ~/Pictures/dotfiles-wallpapers"

gsettings set org.gnome.desktop.interface icon-theme "Yaru-sage"
gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaMono Nerd Font Mono 11'

log_success "Initial theme set (osaka-jade)"
